### PR TITLE
Typhoid vignette

### PR DESCRIPTION
**Pull request by kristinawlai**
I finished the typhoid vignette withe the simulated data and moved the references.bib to the vignettes folder. However, Kristen recommended using the South Sudan data for this vignette so it's real data. The simulated data doesn't have age groups, so it's just overall incidence. I can make those updates, but wanted to get this version pushed out first to have something. Would it be useful to have an overall vignette and an age-specific vignette? Or perhaps include both in the same vignette?

### CODE REVIEW

**Comment by kristinawlai** [comment]
@d-morrison Uh oh checks are failing now. Did I use an older version before your fixes?

**Comment by d-morrison** [comment]
> @d-morrison Uh oh checks are failing now. Did I use an older version before your fixes?

@kristinawlai: 

The relevant error is:

`could not find function "load_all"`

The `load_all` function is only for in-development code. The finalized vignettes should use `library(serocalculator)` instead. Try making that change; to test on your local computer, first run the `install()` command in the Console, then replace `load_all()` with `library(serocalculator)`, then run the `test()` command in the Console. If the output of `test()` is all tests passed, then the tests on github should also pass.

**Review by d-morrison — CHANGES_REQUESTED** [review]
(see my reply re: check errors)

**Comment by kristinawlai** [comment]
@d-morrison I removed `load_all()` and `devtools()` from typhoid-seroincidence.rmd and tutorial.rmd, but there are still errors. When I use `test()` in my console there are no errors either, but it has been running so quickly that I don't trust it. Any tips?

**Comment by d-morrison** [comment]
> @d-morrison I removed `load_all()` and `devtools()` from typhoid-seroincidence.rmd and tutorial.rmd, but there are still errors. When I use `test()` in my console there are no errors either, but it has been running so quickly that I don't trust it. Any tips?

@kristinawlai Looks like there is a reference to the "seroincidence" package somewhere: in the checks, there is a message:

````
Error: Error: processing vignette 'tutorial.Rmd' failed with diagnostics:
4 nodes produced errors; first error: there is no package called ‘seroincidence’
```

**Comment by kristinawlai** [comment]
@d-morrison the checks pass now! This is the only warning I saw when checking on my desktop and I'm not quite sure what to do with it. Maybe just a function name issue? 

> W  checking for code/documentation mismatches (1.8s)
   Functions or methods with usage in documentation object 'incidence.age' but not in code:
     'incidence.age'

**Comment by kristinawlai** [comment]
Closing this since all updates were moved to the typhoid_vignette_hack branch

**Pull request closed without merging**
