### PR TITLE
Typhoid vignette hack

### PR DESCRIPTION
**Pull request by kristinawlai**
@d-morrison Updated vignette for enteric fever. Still having trouble getting the est.incidence and est.incidence.by to run, but take a look. As of a few min ago I'm getting the error below for both. 

image

### CODE REVIEW

**Comment by kristinawlai** [comment]
The vignette is running smoothly but checks are failing now. I think it's related to 1) me adding references.bib back in to the vignettes folder, 2) the updated vignette name and title + discrepancies in documentation (inst/doc), and 3) the pkgdown check says the cross-sectional dataset (SEES_2022-10-24_redacted_2023-10-12.csv) does not exist. @d-morrison can you take a look? 

Also @kaiemjoy feel free to review the vignette itself!

**Comment by d-morrison** [comment]
> The vignette is running smoothly but checks are failing now. I think it's related to 1) me adding references.bib back in to the vignettes folder, 2) the updated vignette name and title + discrepancies in documentation (inst/doc), and 3) the pkgdown check says the cross-sectional dataset (SEES_2022-10-24_redacted_2023-10-12.csv) does not exist. @d-morrison can you take a look?
> 
> Also @kaiemjoy feel free to review the vignette itself!

@kristinawlai I'll take a look!

**Comment by kristinawlai** [comment]
Ready to merge once reviewed

**Review by d-morrison — DISMISSED** [review]
Looks great!

**Review by d-morrison — APPROVED** [review]
great work!!

**Pull request merged**
