### PR TITLE
merge main into typhoid_vignette

### PR DESCRIPTION
**Pull request by d-morrison**

### CODE REVIEW

**Review by kristinawlai — APPROVED** [review]

**Comment by kristinawlai** [comment]
@d-morrison I'm stuck on how to resolve these conflicts in the command line.

**Comment by d-morrison** [comment]
> @d-morrison I'm stuck on how to resolve these conflicts in the command line. 

@kristinawlai I'll take a look!

**Comment by kristinawlai** [comment]
@d-morrison I don't think we need this branch anymore?

**Comment by d-morrison** [comment]
agreed; I'll close it

**Pull request closed without merging**
